### ISSUE TITLE
Test Dependencies

### ISSUE THREAD

**Issue by MartinNoc** [OWASP/owasp-istg#11]
Test cases in Physical Interface, Wireless Interface, and User Interface are based on test cases in Firmware and Data Exchange Service.
Does "based on" mean that these tests (e.g. ISTG-FW-INFO-002) have to be performed prior to performing the interface test (e.g. [ISTG-PHY-INFO-001](https://github.com/OWASP/owasp-istg/tree/main/src/03_test_cases/physical_interfaces#disclosure-of-implementation-details-istg-phy-info-001))?

If yes, this is not ideally represented in [this Table](https://github.com/OWASP/owasp-istg/blob/main/src/02_framework/attacker_model.md#mapping-of-device-components-and-access-levels). An example: Wireless Interface test can be conducted with physical access level PA-2, while the firmware might not be available with PA-2. However, Wireless Interface tests are based on Firmware tests.

Thanks for clarification!
Best, Martin

**Comment by MartinNoc** [comment]
@scriptingxss 
@rockhoppersec 
Thanks in advance :)

**Comment by rockhoppersec** [comment]
Hi Martin,

Thanks for bringing this up and sorry for the late response.

In short: No, there are no dependencies between test cases for different components. So, each component can be tested individually on its own.

"This test case is based on: [...]" means that the test case (partially or completely) mirrors the contents of another test case. It basically means that a test case was not created out of thin air but copied from another component, because it can be applied to both. 

For example, in case of ISTG-PHY-INFO-001, "this test case is based on: ISTG-FW-INFO-002" means that the test case was initially created for the firmware component (as ISTG-FW-INFO-002), but is "reused" by the component physical interfaces (as ISTG-PHY-INFO-001), because it applies to both and testers need to consider it when testing firmware or physical interfaces, etc.

Hope this clears things up. Feel free to let me know if not.

**Comment by MartinNoc** [comment]
Dear @rockhoppersec 
Thanks for clearing up. Perfectly explained! :)
Best, Martin
